/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AvatarDemo: typeof import('./src/components/docs/AvatarDemo.vue')['default']
    BadgeDemo: typeof import('./src/components/docs/BadgeDemo.vue')['default']
    BreadcrumbDemo: typeof import('./src/components/docs/BreadcrumbDemo.vue')['default']
    ButtonDemo: typeof import('./src/components/docs/ButtonDemo.vue')['default']
    CardDemo: typeof import('./src/components/docs/CardDemo.vue')['default']
    CheckboxDemo: typeof import('./src/components/docs/CheckboxDemo.vue')['default']
    CodeCollapsible: typeof import('./src/components/docs/CodeCollapsible.vue')['default']
    DashListDemo: typeof import('./src/components/docs/DashListDemo.vue')['default']
    DataTableDemo: typeof import('./src/components/docs/DataTableDemo.vue')['default']
    DemoTabs: typeof import('./src/components/docs/DemoTabs.vue')['default']
    DropdownMenuDemo: typeof import('./src/components/docs/DropdownMenuDemo.vue')['default']
    IconsDemo: typeof import('./src/components/docs/IconsDemo.vue')['default']
    InputDemo: typeof import('./src/components/docs/InputDemo.vue')['default']
    KbdDemo: typeof import('./src/components/docs/KbdDemo.vue')['default']
    MetricDemo: typeof import('./src/components/docs/MetricDemo.vue')['default']
    ModalDemo: typeof import('./src/components/docs/ModalDemo.vue')['default']
    PaginationDemo: typeof import('./src/components/docs/PaginationDemo.vue')['default']
    PopoverDemo: typeof import('./src/components/docs/PopoverDemo.vue')['default']
    ProgressDemo: typeof import('./src/components/docs/ProgressDemo.vue')['default']
    QuoteDemo: typeof import('./src/components/docs/QuoteDemo.vue')['default']
    SelectDemo: typeof import('./src/components/docs/SelectDemo.vue')['default']
    SkeletonDemo: typeof import('./src/components/docs/SkeletonDemo.vue')['default']
    SwitchDemo: typeof import('./src/components/docs/SwitchDemo.vue')['default']
    TabsDemo: typeof import('./src/components/docs/TabsDemo.vue')['default']
    TextareaDemo: typeof import('./src/components/docs/TextareaDemo.vue')['default']
    TooltipDemo: typeof import('./src/components/docs/TooltipDemo.vue')['default']
    UAvatar: typeof import('./node_modules/.pnpm/@nuxt+ui@4.9.0_patch_hash=9_b58c1b34b6afe30493d7db853e29d06d/node_modules/@nuxt/ui/dist/runtime/components/Avatar.vue')['default']
    UBadge: typeof import('./node_modules/.pnpm/@nuxt+ui@4.9.0_patch_hash=9_b58c1b34b6afe30493d7db853e29d06d/node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UBreadcrumb: typeof import('./node_modules/.pnpm/@nuxt+ui@4.9.0_patch_hash=9_b58c1b34b6afe30493d7db853e29d06d/node_modules/@nuxt/ui/dist/runtime/components/Breadcrumb.vue')['default']
    UButton: typeof import('./node_modules/.pnpm/@nuxt+ui@4.9.0_patch_hash=9_b58c1b34b6afe30493d7db853e29d06d/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCard: typeof import('./node_modules/.pnpm/@nuxt+ui@4.9.0_patch_hash=9_b58c1b34b6afe30493d7db853e29d06d/node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UCheckbox: typeof import('./node_modules/.pnpm/@nuxt+ui@4.9.0_patch_hash=9_b58c1b34b6afe30493d7db853e29d06d/node_modules/@nuxt/ui/dist/runtime/components/Checkbox.vue')['default']
    UDropdownMenu: typeof import('./node_modules/.pnpm/@nuxt+ui@4.9.0_patch_hash=9_b58c1b34b6afe30493d7db853e29d06d/node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.vue')['default']
    UFieldGroup: typeof import('./node_modules/.pnpm/@nuxt+ui@4.9.0_patch_hash=9_b58c1b34b6afe30493d7db853e29d06d/node_modules/@nuxt/ui/dist/runtime/components/FieldGroup.vue')['default']
    UFormField: typeof import('./node_modules/.pnpm/@nuxt+ui@4.9.0_patch_hash=9_b58c1b34b6afe30493d7db853e29d06d/node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UInput: typeof import('./node_modules/.pnpm/@nuxt+ui@4.9.0_patch_hash=9_b58c1b34b6afe30493d7db853e29d06d/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UKbd: typeof import('./node_modules/.pnpm/@nuxt+ui@4.9.0_patch_hash=9_b58c1b34b6afe30493d7db853e29d06d/node_modules/@nuxt/ui/dist/runtime/components/Kbd.vue')['default']
    UModal: typeof import('./node_modules/.pnpm/@nuxt+ui@4.9.0_patch_hash=9_b58c1b34b6afe30493d7db853e29d06d/node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
    UPagination: typeof import('./node_modules/.pnpm/@nuxt+ui@4.9.0_patch_hash=9_b58c1b34b6afe30493d7db853e29d06d/node_modules/@nuxt/ui/dist/runtime/components/Pagination.vue')['default']
    UPopover: typeof import('./node_modules/.pnpm/@nuxt+ui@4.9.0_patch_hash=9_b58c1b34b6afe30493d7db853e29d06d/node_modules/@nuxt/ui/dist/runtime/components/Popover.vue')['default']
    UProgress: typeof import('./node_modules/.pnpm/@nuxt+ui@4.9.0_patch_hash=9_b58c1b34b6afe30493d7db853e29d06d/node_modules/@nuxt/ui/dist/runtime/components/Progress.vue')['default']
    USelect: typeof import('./node_modules/.pnpm/@nuxt+ui@4.9.0_patch_hash=9_b58c1b34b6afe30493d7db853e29d06d/node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
    USelectMenu: typeof import('./node_modules/.pnpm/@nuxt+ui@4.9.0_patch_hash=9_b58c1b34b6afe30493d7db853e29d06d/node_modules/@nuxt/ui/dist/runtime/components/SelectMenu.vue')['default']
    USwitch: typeof import('./node_modules/.pnpm/@nuxt+ui@4.9.0_patch_hash=9_b58c1b34b6afe30493d7db853e29d06d/node_modules/@nuxt/ui/dist/runtime/components/Switch.vue')['default']
    UTabs: typeof import('./node_modules/.pnpm/@nuxt+ui@4.9.0_patch_hash=9_b58c1b34b6afe30493d7db853e29d06d/node_modules/@nuxt/ui/dist/runtime/components/Tabs.vue')['default']
    UTextarea: typeof import('./node_modules/.pnpm/@nuxt+ui@4.9.0_patch_hash=9_b58c1b34b6afe30493d7db853e29d06d/node_modules/@nuxt/ui/dist/runtime/components/Textarea.vue')['default']
    UTooltip: typeof import('./node_modules/.pnpm/@nuxt+ui@4.9.0_patch_hash=9_b58c1b34b6afe30493d7db853e29d06d/node_modules/@nuxt/ui/dist/runtime/components/Tooltip.vue')['default']
  }
}
