import js from "@eslint/js";
import tseslint from "typescript-eslint";
import pluginVue from "eslint-plugin-vue";
import prettier from "eslint-config-prettier";
import globals from "globals";

export default tseslint.config(
  // Ignore patterns
  {
    ignores: [
      "**/dist/**",
      "**/node_modules/**",
      "**/.astro/**",
      "**/coverage/**",
      "packages/tokens/src/index.ts", // auto-generated by build.ts
    ],
  },

  // Base JS recommended rules
  js.configs.recommended,

  // TypeScript recommended rules - disable no-undef (TS handles it)
  ...tseslint.configs.recommended,

  // TS overrides: disable no-undef for all TS files
  {
    files: ["**/*.{ts,tsx}"],
    rules: {
      "no-undef": "off",
    },
  },

  // Vue SFC files: browser globals + TypeScript parser
  {
    files: ["**/*.vue"],
    languageOptions: {
      globals: {
        ...globals.browser,
      },
      parserOptions: {
        parser: tseslint.parser,
      },
    },
    rules: {
      "no-undef": "off",
    },
  },

  // Vue recommended rules
  ...pluginVue.configs["flat/recommended"],

  // Browser globals (.js files in public/)
  {
    files: ["public/**/*.js"],
    languageOptions: {
      globals: {
        ...globals.browser,
      },
    },
  },

  // Node.js scripts (.mjs files)
  {
    files: ["**/*.mjs"],
    languageOptions: {
      globals: {
        ...globals.node,
      },
    },
  },

  // Custom rules (applied to all files)
  {
    rules: {
      "@typescript-eslint/no-unused-vars": ["warn", { argsIgnorePattern: "^_" }],
      "@typescript-eslint/no-explicit-any": "warn",
      "vue/multi-word-component-names": "off",
    },
  },

  // Prettier integration (must be last)
  prettier
);
