/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const defineLocale: typeof import('../../node_modules/.pnpm/@nuxt+ui@4.9.0_patch_hash=98f5908bcab9fd790fc13a7aeffe76aaa66373615c18401f94b90a8c726f7_6ac119eb10beeaadbb753edcf5861f7c/node_modules/@nuxt/ui/dist/runtime/composables/defineLocale').defineLocale
  const defineShortcuts: typeof import('../../node_modules/.pnpm/@nuxt+ui@4.9.0_patch_hash=98f5908bcab9fd790fc13a7aeffe76aaa66373615c18401f94b90a8c726f7_6ac119eb10beeaadbb753edcf5861f7c/node_modules/@nuxt/ui/dist/runtime/composables/defineShortcuts').defineShortcuts
  const extendLocale: typeof import('../../node_modules/.pnpm/@nuxt+ui@4.9.0_patch_hash=98f5908bcab9fd790fc13a7aeffe76aaa66373615c18401f94b90a8c726f7_6ac119eb10beeaadbb753edcf5861f7c/node_modules/@nuxt/ui/dist/runtime/composables/defineLocale').extendLocale
  const extractShortcuts: typeof import('../../node_modules/.pnpm/@nuxt+ui@4.9.0_patch_hash=98f5908bcab9fd790fc13a7aeffe76aaa66373615c18401f94b90a8c726f7_6ac119eb10beeaadbb753edcf5861f7c/node_modules/@nuxt/ui/dist/runtime/composables/defineShortcuts').extractShortcuts
  const useAppConfig: typeof import('../../node_modules/.pnpm/@nuxt+ui@4.9.0_patch_hash=98f5908bcab9fd790fc13a7aeffe76aaa66373615c18401f94b90a8c726f7_6ac119eb10beeaadbb753edcf5861f7c/node_modules/@nuxt/ui/dist/runtime/vue/composables/useAppConfig.js').useAppConfig
  const useContentSearch: typeof import('../../node_modules/.pnpm/@nuxt+ui@4.9.0_patch_hash=98f5908bcab9fd790fc13a7aeffe76aaa66373615c18401f94b90a8c726f7_6ac119eb10beeaadbb753edcf5861f7c/node_modules/@nuxt/ui/dist/runtime/composables/useContentSearch').useContentSearch
  const useFileUpload: typeof import('../../node_modules/.pnpm/@nuxt+ui@4.9.0_patch_hash=98f5908bcab9fd790fc13a7aeffe76aaa66373615c18401f94b90a8c726f7_6ac119eb10beeaadbb753edcf5861f7c/node_modules/@nuxt/ui/dist/runtime/composables/useFileUpload').useFileUpload
  const useFormField: typeof import('../../node_modules/.pnpm/@nuxt+ui@4.9.0_patch_hash=98f5908bcab9fd790fc13a7aeffe76aaa66373615c18401f94b90a8c726f7_6ac119eb10beeaadbb753edcf5861f7c/node_modules/@nuxt/ui/dist/runtime/composables/useFormField').useFormField
  const useKbd: typeof import('../../node_modules/.pnpm/@nuxt+ui@4.9.0_patch_hash=98f5908bcab9fd790fc13a7aeffe76aaa66373615c18401f94b90a8c726f7_6ac119eb10beeaadbb753edcf5861f7c/node_modules/@nuxt/ui/dist/runtime/composables/useKbd').useKbd
  const useOverlay: typeof import('../../node_modules/.pnpm/@nuxt+ui@4.9.0_patch_hash=98f5908bcab9fd790fc13a7aeffe76aaa66373615c18401f94b90a8c726f7_6ac119eb10beeaadbb753edcf5861f7c/node_modules/@nuxt/ui/dist/runtime/composables/useOverlay').useOverlay
  const useResizable: typeof import('../../node_modules/.pnpm/@nuxt+ui@4.9.0_patch_hash=98f5908bcab9fd790fc13a7aeffe76aaa66373615c18401f94b90a8c726f7_6ac119eb10beeaadbb753edcf5861f7c/node_modules/@nuxt/ui/dist/runtime/composables/useResizable').useResizable
  const useScrollShadow: typeof import('../../node_modules/.pnpm/@nuxt+ui@4.9.0_patch_hash=98f5908bcab9fd790fc13a7aeffe76aaa66373615c18401f94b90a8c726f7_6ac119eb10beeaadbb753edcf5861f7c/node_modules/@nuxt/ui/dist/runtime/composables/useScrollShadow').useScrollShadow
  const useScrollspy: typeof import('../../node_modules/.pnpm/@nuxt+ui@4.9.0_patch_hash=98f5908bcab9fd790fc13a7aeffe76aaa66373615c18401f94b90a8c726f7_6ac119eb10beeaadbb753edcf5861f7c/node_modules/@nuxt/ui/dist/runtime/composables/useScrollspy').useScrollspy
  const useToast: typeof import('../../node_modules/.pnpm/@nuxt+ui@4.9.0_patch_hash=98f5908bcab9fd790fc13a7aeffe76aaa66373615c18401f94b90a8c726f7_6ac119eb10beeaadbb753edcf5861f7c/node_modules/@nuxt/ui/dist/runtime/composables/useToast').useToast
  const useTour: typeof import('../../node_modules/.pnpm/@nuxt+ui@4.9.0_patch_hash=98f5908bcab9fd790fc13a7aeffe76aaa66373615c18401f94b90a8c726f7_6ac119eb10beeaadbb753edcf5861f7c/node_modules/@nuxt/ui/dist/runtime/composables/useTour').useTour
}
