/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    MizuDashList: typeof import('./src/components/MizuDashList.vue')['default']
    MizuMetric: typeof import('./src/components/MizuMetric.vue')['default']
    MizuQuote: typeof import('./src/components/MizuQuote.vue')['default']
    MizuSkeleton: typeof import('./src/components/MizuSkeleton.vue')['default']
  }
}
