/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    MizuDashList: typeof import('./src/components/MizuDashList.vue')['default']
    MizuDateField: typeof import('./src/components/MizuDateField.vue')['default']
    MizuMetric: typeof import('./src/components/MizuMetric.vue')['default']
    MizuQuote: typeof import('./src/components/MizuQuote.vue')['default']
    MizuSkeleton: typeof import('./src/components/MizuSkeleton.vue')['default']
    UCalendar: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.9.0_patch_hash=98f5908bcab9fd790fc13a7aeffe76aaa66373615c18401f94b90a8c726f7_6ac119eb10beeaadbb753edcf5861f7c/node_modules/@nuxt/ui/dist/runtime/components/Calendar.vue')['default']
    UPopover: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.9.0_patch_hash=98f5908bcab9fd790fc13a7aeffe76aaa66373615c18401f94b90a8c726f7_6ac119eb10beeaadbb753edcf5861f7c/node_modules/@nuxt/ui/dist/runtime/components/Popover.vue')['default']
  }
}
