import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "../../..");
const TOKENS_PATH = resolve(ROOT, "tokens.json");
const OUT_DIR = resolve(__dirname, "../dist");
const SRC_OUT = resolve(__dirname, "../src");

interface Token {
  $value: string | number | string[];
  $type: string;
  $description?: string;
}

interface TokenGroup {
  [key: string]: Token | TokenGroup;
}

function isToken(obj: unknown): obj is Token {
  return obj !== null && typeof obj === "object" && "$value" in (obj as Record<string, unknown>);
}

function flattenTokens(obj: TokenGroup | Token, prefix: string[] = []): Map<string, Token> {
  const result = new Map<string, Token>();

  for (const [key, value] of Object.entries(obj)) {
    const path = [...prefix, key];

    if (isToken(value)) {
      result.set(path.join("/"), value);
    } else if (typeof value === "object" && value !== null) {
      const nested = flattenTokens(value as TokenGroup, path);
      for (const [k, v] of nested) {
        result.set(k, v);
      }
    }
  }

  return result;
}

function toCamelCase(segments: string[]): string {
  return segments.map((s, i) => (i === 0 ? s : s.charAt(0).toUpperCase() + s.slice(1))).join("");
}

function toConstName(segments: string[]): string {
  return segments.map((s) => s.replace(/-/g, "_").toUpperCase()).join("_");
}

function toConstNameFromPath(path: string): string {
  return toConstName(path.split("/"));
}

function generateType(value: unknown): string {
  if (typeof value === "number") return "number";
  if (Array.isArray(value)) return "string[]";
  return "string";
}

function generateValue(value: unknown, type: string): string {
  if (type === "number") return String(value);
  return JSON.stringify(value);
}

/**
 * Convert a token path (slash-separated) into a flat list of hyphenated segments.
 */
function pathToSegments(path: string): string[] {
  return path.split("/");
}

/**
 * Map a token path to a @theme variable name (Tailwind v4 convention).
 */
function toThemeVarName(path: string): string {
  const segments = pathToSegments(path);
  const root = segments[0];
  const rest = segments
    .slice(1)
    .map((s) => camelToKebab(s))
    .join("-");

  switch (root) {
    case "color":
      return `--color-${rest}`;
    case "fontFamily":
      return `--font-family-${rest}`;
    case "fontSize":
      return `--text-${rest}`;
    case "fontWeight":
      return `--font-weight-${rest}`;
    case "lineHeight":
      return `--leading-${rest}`;
    case "letterSpacing":
      return `--tracking-${rest}`;
    case "shadow":
      return `--shadow-${rest}`;
    case "sizing":
      return `--sizing-${rest}`;
    case "zIndex":
      return `--z-${rest}`;
    case "duration":
      return `--duration-${rest}`;
    case "ease":
      return `--ease-${rest}`;
    default:
      return `--${segments.join("-")}`;
  }
}

/**
 * Format a token value for use as a CSS custom property value.
 * Font-family arrays become comma-separated quoted strings.
 */
function formatCssValue(value: unknown, type: string): string {
  if (type === "fontFamily" && Array.isArray(value)) {
    return value.map((name) => (/[\s"]/.test(name) ? `"${name}"` : name)).join(", ");
  }
  return String(value);
}

/**
 * Map a token path to a raw CSS variable name (kebab-case segments).
 * For dark tokens, the "dark" segment is dropped so the var overrides its light counterpart.
 */
function toCssVarName(path: string): string {
  const segments = pathToSegments(path);
  if (segments[1] === "dark" && (segments[0] === "color" || segments[0] === "shadow")) {
    return `--${segments[0]}-${segments.slice(2).join("-")}`;
  }
  return `--${segments.map((s) => camelToKebab(s)).join("-")}`;
}

function camelToKebab(s: string): string {
  return s.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();
}

function generateTsSource(flat: Map<string, Token>): string {
  const lines: string[] = [];
  lines.push("// Auto-generated by build.ts — do not edit manually");
  lines.push(`// Source: tokens.json`);
  lines.push("");
  lines.push("export interface Token {");
  lines.push("  value: string | number | readonly string[];");
  lines.push("  type: string;");
  lines.push("  description?: string;");
  lines.push("}");
  lines.push("");

  for (const [path, token] of flat) {
    const segments = pathToSegments(path);
    const constName = toConstName(segments);
    const value = generateValue(token.$value, token.$type);
    const isFontFamily = token.$type === "fontFamily";

    lines.push(`/** ${token.$description ?? path} */`);
    if (isFontFamily) {
      lines.push(`export const ${constName}: string[] = ${value};`);
    } else {
      lines.push(`export const ${constName} = ${value} as const;`);
    }
  }

  lines.push("");

  lines.push("/** Flat map of all tokens keyed by slash-separated path */");
  lines.push("export const tokens: Record<string, Token> = {");
  for (const [path, token] of flat) {
    const constName = toConstNameFromPath(path);
    lines.push(`  "${path}": { value: ${constName}, type: "${token.$type}" },`);
  }
  lines.push("};");
  lines.push("");

  lines.push(
    "/** Token values mapped to CSS custom property names (light mode only — dark mode overrides live in dark.css) */"
  );
  lines.push("export const cssVariables: Record<string, string | number | readonly string[]> = {");
  for (const [path, token] of flat) {
    if (isDarkPath(path)) continue;
    const cssVar = toCssVarName(path);
    const constName = toConstNameFromPath(path);
    lines.push(`  "${cssVar}": ${constName},`);
  }
  lines.push("}");
  lines.push("");

  return lines.join("\n");
}

function generateLightCss(flat: Map<string, Token>): string {
  const lines: string[] = [];
  lines.push("/* Auto-generated by build.ts — do not edit manually */");
  lines.push("/* Source: tokens.json — light-mode CSS custom properties */");
  lines.push("");
  lines.push(":root {");
  for (const [path, token] of flat) {
    if (isDarkPath(path)) continue;
    const cssVar = toCssVarName(path);
    const value = formatCssValue(token.$value, token.$type);
    lines.push(`  ${cssVar}: ${value};`);
  }
  lines.push("}");
  lines.push("");
  return lines.join("\n");
}

function generateDarkCss(flat: Map<string, Token>): string {
  const lines: string[] = [];
  lines.push("/* Auto-generated by build.ts — do not edit manually */");
  lines.push("/* Source: tokens.json — dark-mode CSS custom property overrides */");
  lines.push("");
  lines.push('[data-theme="dark"] {');
  for (const [path, token] of flat) {
    if (!isDarkPath(path)) continue;
    const cssVar = toCssVarName(path);
    const value = formatCssValue(token.$value, token.$type);
    lines.push(`  ${cssVar}: ${value};`);
  }
  lines.push("}");
  lines.push("");
  return lines.join("\n");
}

function generateTailwindCss(flat: Map<string, Token>): string {
  const lines: string[] = [];
  lines.push("/* Auto-generated by build.ts — do not edit manually */");
  lines.push("/* Source: tokens.json — Tailwind v4 @theme tokens + dark overrides */");
  lines.push("");
  // @import "tailwindcss" is handled by @tailwindcss/vite plugin
  // lines.push('@import "tailwindcss";');
  lines.push("");
  lines.push("@theme {");

  // Font-family shortcuts so Tailwind generates `font-sans` / `font-mono` / `font-serif`.
  const fontFamilies: Array<{ key: string; segments: string[]; cssValue: string }> = [];
  for (const [path, token] of flat) {
    if (isDarkPath(path)) continue;
    const segments = pathToSegments(path);
    const themeVar = toThemeVarName(path);
    const value = formatCssValue(token.$value, token.$type);
    lines.push(`  ${themeVar}: ${value};`);
    if (segments[0] === "fontFamily") {
      const aliasName = segments[1];
      fontFamilies.push({
        key: aliasName,
        segments,
        cssValue: `var(--font-family-${aliasName})`,
      });
    }
  }

  for (const ff of fontFamilies) {
    lines.push(`  --font-${ff.key}: ${ff.cssValue};`);
  }

  lines.push("}");
  lines.push("");

  lines.push('[data-theme="dark"] {');
  for (const [path, token] of flat) {
    if (!isDarkPath(path)) continue;
    const segments = pathToSegments(path);
    const themeVar = `--${segments[0]}-${segments.slice(2).join("-")}`;
    const value = formatCssValue(token.$value, token.$type);
    lines.push(`  ${themeVar}: ${value};`);
  }
  lines.push("}");
  lines.push("");

  return lines.join("\n");
}

/**
 * A path is "dark" if its second segment is "dark" (e.g. color/dark/... or shadow/dark/...).
 * The dark segment is dropped when emitting CSS variables so the dark value overrides
 * the light value at the same var name.
 */
function isDarkPath(path: string): boolean {
  const segments = pathToSegments(path);
  return segments[1] === "dark" && (segments[0] === "color" || segments[0] === "shadow");
}

/**
 * Map Mizu tokens to Starlight's --sl-* variable names.
 * Anything that doesn't have a clean Mizu equivalent (the gray ramp) is hardcoded
 * but kept here so this file remains the single source for Starlight theming.
 */
function generateStarlightCss(flat: Map<string, Token>): string {
  const lightGray = [
    "#FFFFFF",
    "#F9FAFB",
    "#F3F4F6",
    "#E5E7EB",
    "#D1D5DB",
    "#9CA3AF",
    "#6B7280",
    "#4B5563",
    "#1B1B1D",
  ];
  const darkGray = [
    "#0F1117",
    "#161822",
    "#1E2030",
    "#2A2D3E",
    "#3B3F52",
    "#64748B",
    "#94A3B8",
    "#CBD5E1",
    "#F1F5F9",
  ];

  const lines: string[] = [];
  lines.push("/* Auto-generated by build.ts — do not edit manually */");
  lines.push("/* Source: tokens.json — Starlight theme variable mappings */");
  lines.push("");
  lines.push(":root,");
  lines.push('[data-theme="light"],');
  lines.push(".sl-theme-light {");
  lines.push("  color-scheme: light;");
  lines.push("");
  lines.push("  /* Accent */");
  lines.push("  --sl-color-accent: var(--color-hub-ycp);");
  lines.push("  --sl-color-accent-high: var(--color-hub-primary);");
  lines.push("  --sl-color-accent-low: var(--color-hub-primary-subtle);");
  lines.push("  --sl-color-accent-subtle: var(--color-hub-ycp-subtle);");
  lines.push("");
  lines.push("  /* Gray ramp — Starlight requires a 9-step scale; Mizu does not emit one */");
  for (let i = 0; i < lightGray.length; i++) {
    lines.push(`  --sl-color-gray-${i + 1}: ${lightGray[i]};`);
  }
  lines.push("");
  lines.push("  /* Text */");
  lines.push("  --sl-color-text: var(--color-foreground-primary);");
  lines.push("  --sl-color-text-light: var(--color-foreground-secondary);");
  lines.push("  --sl-color-text-lighter: var(--color-foreground-tertiary);");
  lines.push("  --sl-color-text-accent: var(--color-hub-primary);");
  lines.push("");
  lines.push("  /* Background */");
  lines.push("  --sl-color-bg: var(--color-surface-base);");
  lines.push("  --sl-color-bg-nav: var(--color-surface-subtle);");
  lines.push("  --sl-color-bg-sidebar: var(--color-surface-subtle);");
  lines.push("  --sl-color-bg-inline-code: var(--color-surface-muted);");
  lines.push("  --sl-color-black: #1B1B1D;");
  lines.push("  --sl-color-white: #FFFFFF;");
  lines.push("");
  lines.push("  /* Borders */");
  lines.push("  --sl-color-hairline: var(--color-surface-muted);");
  lines.push("  --sl-color-hairline-shade: var(--color-surface-muted);");
  lines.push("");
  lines.push("  /* Fonts */");
  lines.push("  --sl-font: var(--font-family-sans);");
  lines.push("  --sl-font-mono: var(--font-family-mono);");
  lines.push("");
  lines.push("  /* Type scale */");
  lines.push("  --sl-text-h1: 1.5rem;");
  lines.push("  --sl-text-h2: 1.125rem;");
  lines.push("  --sl-text-h3: 0.9375rem;");
  lines.push("  --sl-text-h4: 0.9375rem;");
  lines.push("  --sl-text-h5: 0.8125rem;");
  lines.push("  --sl-text-h6: 0.6875rem;");
  lines.push("  --sl-text-code: 0.8125rem;");
  lines.push("  --sl-text-base: 0.9375rem;");
  lines.push("  --sl-text-sm: 0.8125rem;");
  lines.push("  --sl-text-xs: 0.6875rem;");
  lines.push("  --sl-text-2xs: 0.625rem;");
  lines.push("");
  lines.push("  /* Layout */");
  lines.push("  --sl-line-height: 1.6;");
  lines.push("  --sl-line-height-headings: 1.2;");
  lines.push("");
  lines.push("  /* Radius */");
  lines.push("  --sl-radius-sm: var(--radius-tight);");
  lines.push("  --sl-radius-md: var(--radius-default);");
  lines.push("  --sl-radius-lg: var(--radius-card);");
  lines.push("  --sl-radius-xl: var(--radius-feature);");
  lines.push("  --sl-radius-full: var(--radius-full);");
  lines.push("");
  lines.push("  /* Content */");
  lines.push("  --sl-content-width: 45rem;");
  lines.push("}");
  lines.push("");
  lines.push('[data-theme="dark"],');
  lines.push(".sl-theme-dark {");
  lines.push("  color-scheme: dark;");
  lines.push("");
  lines.push("  /* Accent */");
  lines.push("  --sl-color-accent: var(--color-hub-ycp);");
  lines.push("  --sl-color-accent-high: var(--color-hub-primary);");
  lines.push("  --sl-color-accent-low: var(--color-hub-primary-subtle);");
  lines.push("  --sl-color-accent-subtle: var(--color-hub-ycp-subtle);");
  lines.push("");
  lines.push("  /* Gray ramp */");
  for (let i = 0; i < darkGray.length; i++) {
    lines.push(`  --sl-color-gray-${i + 1}: ${darkGray[i]};`);
  }
  lines.push("");
  lines.push("  /* Text */");
  lines.push("  --sl-color-text: var(--color-foreground-primary);");
  lines.push("  --sl-color-text-light: var(--color-foreground-secondary);");
  lines.push("  --sl-color-text-lighter: var(--color-foreground-tertiary);");
  lines.push("  --sl-color-text-accent: var(--color-hub-primary);");
  lines.push("");
  lines.push("  /* Background */");
  lines.push("  --sl-color-bg: var(--color-surface-base);");
  lines.push("  --sl-color-bg-nav: var(--color-surface-subtle);");
  lines.push("  --sl-color-bg-sidebar: var(--color-surface-subtle);");
  lines.push("  --sl-color-bg-inline-code: var(--color-surface-muted);");
  lines.push("  --sl-color-black: #1B1B1D;");
  lines.push("  --sl-color-white: #FFFFFF;");
  lines.push("");
  lines.push("  /* Borders */");
  lines.push("  --sl-color-hairline: var(--color-surface-muted);");
  lines.push("  --sl-color-hairline-shade: var(--color-surface-muted);");
  lines.push("");
  lines.push("  /* Fonts */");
  lines.push("  --sl-font: var(--font-family-sans);");
  lines.push("  --sl-font-mono: var(--font-family-mono);");
  lines.push("");
  lines.push("  /* Type scale */");
  lines.push("  --sl-text-h1: 1.5rem;");
  lines.push("  --sl-text-h2: 1.125rem;");
  lines.push("  --sl-text-h3: 0.9375rem;");
  lines.push("  --sl-text-h4: 0.9375rem;");
  lines.push("  --sl-text-h5: 0.8125rem;");
  lines.push("  --sl-text-h6: 0.6875rem;");
  lines.push("  --sl-text-code: 0.8125rem;");
  lines.push("  --sl-text-base: 0.9375rem;");
  lines.push("  --sl-text-sm: 0.8125rem;");
  lines.push("  --sl-text-xs: 0.6875rem;");
  lines.push("  --sl-text-2xs: 0.625rem;");
  lines.push("");
  lines.push("  /* Layout */");
  lines.push("  --sl-line-height: 1.6;");
  lines.push("  --sl-line-height-headings: 1.2;");
  lines.push("");
  lines.push("  /* Radius */");
  lines.push("  --sl-radius-sm: var(--radius-tight);");
  lines.push("  --sl-radius-md: var(--radius-default);");
  lines.push("  --sl-radius-lg: var(--radius-card);");
  lines.push("  --sl-radius-xl: var(--radius-feature);");
  lines.push("  --sl-radius-full: var(--radius-full);");
  lines.push("");
  lines.push("  /* Content */");
  lines.push("  --sl-content-width: 45rem;");
  lines.push("}");
  lines.push("");

  // ── Mizu heading typography (per-level weights, tracking, leading) ──
  lines.push("/* Heading typography — weights, letter-spacing, and per-level line-height */");
  lines.push(".sl-markdown-content h1 { font-weight: 700; letter-spacing: -0.02em; line-height: 1.2; }");
  lines.push(".sl-markdown-content h2 { font-weight: 600; line-height: 1.25; }");
  lines.push(".sl-markdown-content h3 { font-weight: 600; line-height: 1.3; }");
  lines.push(".sl-markdown-content h4 { font-weight: 600; }");
  lines.push(".sl-markdown-content h5 { font-weight: 500; }");
  lines.push(".sl-markdown-content h6 { font-weight: 500; }");
  lines.push("");
  lines.push("/* Body text */");
  lines.push(".sl-markdown-content { font-weight: 400; }");
  lines.push("");

  // ── Starlight element fixes (white-on-white + sidebar/TOC typography) ──
  lines.push("/* ── Page title (Starlight defaults to --sl-color-white → invisible in light) ── */");
  lines.push("h1#_top {");
  lines.push("  color: var(--sl-color-text) !important;");
  lines.push("}");
  lines.push("");

  lines.push("/* ── Sidebar ──────────────────────────────────────── */");
  lines.push("/* Section labels (e.g. \"Getting Started\", \"Components\") */");
  lines.push("nav.sidebar-pane summary,");
  lines.push(".sidebar-pane summary {");
  lines.push("  font-weight: 600;");
  lines.push("  font-size: 0.6875rem;      /* text-label: 11px */");

  lines.push("");
  lines.push("}");
  lines.push("");

  lines.push("/* Large sidebar labels */");
  lines.push("nav.sidebar-pane summary .large,");
  lines.push(".sidebar-pane summary .large,");
  lines.push("summary .large {");
  lines.push("  color: var(--sl-color-text) !important;");
  lines.push("}");
  lines.push("");

  lines.push("/* Sidebar nav links */");
  lines.push("nav.sidebar-pane a,");
  lines.push(".sidebar-pane a {");
  lines.push("  font-size: 0.8125rem;      /* text-caption: 13px */");
  lines.push("  font-weight: 400;");
  lines.push("}");
  lines.push("");

  lines.push("/* Active sidebar link */");
  lines.push("nav.sidebar-pane a[aria-current=\"page\"],");
  lines.push(".sidebar-pane a[aria-current=\"page\"] {");
  lines.push("  font-weight: 600;");
  lines.push("}");
  lines.push("");

  lines.push("/* ── Right sidebar / Table of Contents ───────────── */");
  lines.push("nav[data-starlight-toc] a,");
  lines.push(".right-sidebar-panel a {");
  lines.push("  font-size: 0.8125rem;      /* text-caption: 13px */");
  lines.push("  font-weight: 400;");
  lines.push("}");
  lines.push("");

  lines.push("/* ── Color fixes for elements defaulting to --sl-color-white ── */");
  lines.push("/* Collapsible sidebar summary arrows */");
  lines.push(".sidebar-pane summary svg {");
  lines.push("  color: var(--sl-color-text-light);");
  lines.push("}");
  lines.push("");

  lines.push("/* Inline code in sidebar */");
  lines.push(".sidebar-pane code {");
  lines.push("  font-size: 0.6875rem;      /* text-label: 11px */");
  lines.push("}");
  lines.push("");

  lines.push("/* Aside / callout text */");
  lines.push("aside,");
  lines.push(".starlight-aside {");
  lines.push("  color: var(--sl-color-text);");
  lines.push("}");
  lines.push("");

  lines.push("/* Kudos / feedback buttons */");
  lines.push(".starlight-kudos button,");
  lines.push(".starlight-kudos a {");
  lines.push("  color: var(--sl-color-text);");
  lines.push("}");

  return lines.join("\n");
}

function main() {
  console.log("Building @mizu-ui/tokens...");

  const raw = JSON.parse(readFileSync(TOKENS_PATH, "utf-8"));
  const { $schema, description, ...tokenCategories } = raw;

  const flat = flattenTokens(tokenCategories);

  mkdirSync(OUT_DIR, { recursive: true });
  mkdirSync(SRC_OUT, { recursive: true });

  // TypeScript
  const tsSource = generateTsSource(flat);
  writeFileSync(resolve(SRC_OUT, "index.ts"), tsSource);
  writeFileSync(resolve(OUT_DIR, "index.ts"), tsSource);

  // Light + Dark CSS
  const lightCss = generateLightCss(flat);
  writeFileSync(resolve(OUT_DIR, "light.css"), lightCss);

  const darkCss = generateDarkCss(flat);
  writeFileSync(resolve(OUT_DIR, "dark.css"), darkCss);

  // Tailwind v4 @theme
  const tailwindCss = generateTailwindCss(flat);
  writeFileSync(resolve(OUT_DIR, "tailwind.css"), tailwindCss);

  // Starlight
  const starlightCss = generateStarlightCss(flat);
  writeFileSync(resolve(OUT_DIR, "starlight.css"), starlightCss);

  console.log(`Generated ${flat.size} tokens`);
  console.log("Output: dist/{index.ts, light.css, dark.css, tailwind.css, starlight.css}");
}

main();
