import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "../../..");
const TOKENS_PATH = resolve(ROOT, "tokens.json");
const OUT_DIR = resolve(__dirname, "../dist");

interface Token {
  $value: string | number | string[];
  $type: string;
  $description?: string;
}

interface TokenGroup {
  [key: string]: Token | TokenGroup;
}

function isToken(obj: unknown): obj is Token {
  return obj !== null && typeof obj === "object" && "$value" in (obj as Record<string, unknown>);
}

function flattenTokens(
  obj: TokenGroup | Token,
  prefix: string[] = []
): Map<string, Token> {
  const result = new Map<string, Token>();

  for (const [key, value] of Object.entries(obj)) {
    const path = [...prefix, key];

    if (isToken(value)) {
      result.set(path.join("/"), value);
    } else if (typeof value === "object" && value !== null) {
      const nested = flattenTokens(value as TokenGroup, path);
      for (const [k, v] of nested) {
        result.set(k, v);
      }
    }
  }

  return result;
}

function toCamelCase(segments: string[]): string {
  return segments
    .map((s, i) =>
      i === 0 ? s : s.charAt(0).toUpperCase() + s.slice(1)
    )
    .join("");
}

function toConstName(segments: string[]): string {
  return segments.map((s) => s.replace(/-/g, "_").toUpperCase()).join("_");
}

function generateType(value: unknown): string {
  if (typeof value === "number") return "number";
  if (Array.isArray(value)) return "string[]";
  return "string";
}

function generateValue(value: unknown, type: string): string {
  if (type === "number") return String(value);
  if (type === "fontFamily" && Array.isArray(value)) return JSON.stringify(value);
  if (Array.isArray(value)) return JSON.stringify(value);
  return JSON.stringify(value);
}

function main() {
  console.log("Building @mizu/tokens...");

  const raw = JSON.parse(readFileSync(TOKENS_PATH, "utf-8"));
  const { $schema, description, ...tokenCategories } = raw;

  const flat = flattenTokens(tokenCategories);

  mkdirSync(OUT_DIR, { recursive: true });

  // Generate TypeScript source
  const lines: string[] = [];
  lines.push('// Auto-generated by build.ts — do not edit manually');
  lines.push(`// Source: tokens.json`);
  lines.push('');
  lines.push('export interface Token {');
  lines.push('  value: string | number | readonly string[];');
  lines.push('  type: string;');
  lines.push('  description?: string;');
  lines.push('}');
  lines.push('');

  // Generate typed constants
  for (const [path, token] of flat) {
    const segments = path.split("/");
    const constName = toConstName(segments);
    const value = generateValue(token.$value, token.$type);
    const isFontFamily = token.$type === "fontFamily";

    lines.push(`/** ${token.$description ?? path} */`);
    if (isFontFamily) {
      lines.push(`export const ${constName}: string[] = ${value};`);
    } else {
      lines.push(`export const ${constName} = ${value} as const;`);
    }
  }

  lines.push('');

  // Generate grouped object exports
  const groups = new Map<string, Array<{ key: string; constName: string; token: Token }>>();

  for (const [path, token] of flat) {
    const segments = path.split("/");
    const group = segments[0];
    const key = segments.slice(1).join("-") || segments[0];
    const constName = toConstName(segments);

    if (!groups.has(group)) groups.set(group, []);
    groups.get(group)!.push({ key, constName, token });
  }

  // Generate a flat tokens object
  lines.push('/** Flat map of all tokens keyed by slash-separated path */');
  lines.push('export const tokens: Record<string, Token> = {');
  for (const [path, token] of flat) {
    const segments = path.split("/");
    const constName = toConstName(segments);
    lines.push(`  "${path}": { value: ${constName}, type: "${token.$type}" },`);
  }
  lines.push('};');
  lines.push('');

  // Generate CSS variable map
  lines.push('/** Token values mapped to CSS custom property names */');
  lines.push('export const cssVariables: Record<string, string | number | readonly string[]> = {');
  for (const [path, token] of flat) {
    const segments = path.split("/");
    const cssVar = `--${segments.join("-")}`;
    const constName = toConstName(segments);
    lines.push(`  "${cssVar}": ${constName},`);
  }
  lines.push('};');
  lines.push('');

  const tsSource = lines.join("\n");
  writeFileSync(resolve(__dirname, "../src/index.ts"), tsSource);

  // Also copy to dist for direct import
  writeFileSync(resolve(OUT_DIR, "index.ts"), tsSource);

  console.log(`Generated ${flat.size} tokens`);
  console.log(`Output: src/index.ts`);
}

main();
