// Auto-generated by build.ts — do not edit manually
// Source: tokens.json

export interface Token {
  value: string | number | readonly string[];
  type: string;
  description?: string;
}

/** Strongest brand presence for hero emphasis and dark branded surfaces. */
export const COLOR_BRAND_PRIMARY = "#001C44" as const;
/** Darker hover state for primary-filled buttons and nav items. */
export const COLOR_BRAND_PRIMARY_HOVER = "#001536" as const;
/** Deepest primary for focus-visible emphasis and pressed states. */
export const COLOR_BRAND_PRIMARY_FOCUS = "#000F28" as const;
/** Light-tinted primary surface for quiet branded backgrounds. */
export const COLOR_BRAND_PRIMARY_SUBTLE = "#D6E4FF" as const;
/** Supporting brand blue for charts and secondary emphasis. */
export const COLOR_BRAND_SECONDARY = "#1524A9" as const;
/** Darker hover state for secondary brand fills. */
export const COLOR_BRAND_SECONDARY_HOVER = "#101C82" as const;
/** Deepest secondary for focus-visible outlines and pressed states. */
export const COLOR_BRAND_SECONDARY_FOCUS = "#0C1561" as const;
/** Light surface counterpart for secondary branded backgrounds. */
export const COLOR_BRAND_SECONDARY_SUBTLE = "#E1E7FF" as const;
/** Interactive accent for links, focus states, and highlighted controls. */
export const COLOR_BRAND_ACCENT = "#007FFF" as const;
/** Darker hover state for accent-filled buttons and links. */
export const COLOR_BRAND_ACCENT_HOVER = "#0066CC" as const;
/** Deep accent for focus-visible emphasis and active-selected states. */
export const COLOR_BRAND_ACCENT_FOCUS = "#004C99" as const;
/** Light accent-tinted background for info callouts and highlights. */
export const COLOR_BRAND_ACCENT_SUBTLE = "#E0F2FE" as const;
/** Soft brand-tinted surface for subtle highlights and selected rows. */
export const COLOR_BRAND_MUTED = "#EDF0FF" as const;
/** Deep neutral for high-contrast text and key borders. */
export const COLOR_BRAND_NEUTRAL = "#1B1B1D" as const;
/** Default page and card background. Highest-contrast surface. */
export const COLOR_SURFACE_BASE = "#FFFFFF" as const;
/** Secondary surface for grouped sections and side panels. */
export const COLOR_SURFACE_SUBTLE = "#F9FAFB" as const;
/** Tertiary surface for table rows and disabled zones. */
export const COLOR_SURFACE_MUTED = "#F3F4F6" as const;
/** Default high-emphasis text for titles and body copy. */
export const COLOR_FOREGROUND_PRIMARY = "#1B1B1D" as const;
/** Supporting text for descriptions and metadata. */
export const COLOR_FOREGROUND_SECONDARY = "#4B5563" as const;
/** Low-emphasis text for placeholders and disabled content. */
export const COLOR_FOREGROUND_TERTIARY = "#9CA3AF" as const;
/** Text on dark or saturated backgrounds — preserves legibility. */
export const COLOR_FOREGROUND_INVERSE = "#FFFFFF" as const;
/** Primary success for confirmed positive status. */
export const COLOR_FEEDBACK_SUCCESS_BASE = "#15803D" as const;
/** Darker hover for success-filled elements. */
export const COLOR_FEEDBACK_SUCCESS_HOVER = "#166534" as const;
/** Deepest success for focus-visible outlines. */
export const COLOR_FEEDBACK_SUCCESS_FOCUS = "#14532D" as const;
/** Light success background for banners. */
export const COLOR_FEEDBACK_SUCCESS_SUBTLE = "#DCFCE7" as const;
/** Primary error for critical statuses. */
export const COLOR_FEEDBACK_ERROR_BASE = "#DC2626" as const;
/** Darker hover for error-filled elements. */
export const COLOR_FEEDBACK_ERROR_HOVER = "#B91C1C" as const;
/** Deepest error for focus-visible outlines. */
export const COLOR_FEEDBACK_ERROR_FOCUS = "#991B1B" as const;
/** Light error background for error banners. */
export const COLOR_FEEDBACK_ERROR_SUBTLE = "#FEF2F2" as const;
/** Primary warning for caution states, pending indicators. */
export const COLOR_FEEDBACK_WARNING_BASE = "#D97706" as const;
/** Darker hover for warning-filled elements. */
export const COLOR_FEEDBACK_WARNING_HOVER = "#B45309" as const;
/** Deepest warning for focus-visible outlines. */
export const COLOR_FEEDBACK_WARNING_FOCUS = "#92400E" as const;
/** Light amber background for warning banners. */
export const COLOR_FEEDBACK_WARNING_SUBTLE = "#FFFBEB" as const;
/** Primary info for on-progress and processing states. */
export const COLOR_FEEDBACK_INFO_BASE = "#0284C7" as const;
/** Darker hover for info-filled elements. */
export const COLOR_FEEDBACK_INFO_HOVER = "#0369A1" as const;
/** Deepest info for focus-visible outlines. */
export const COLOR_FEEDBACK_INFO_FOCUS = "#075985" as const;
/** Light sky background for info banners. */
export const COLOR_FEEDBACK_INFO_SUBTLE = "#F0F9FF" as const;
/** Dark mode primary — lighter for dark backgrounds. */
export const COLOR_DARK_BRAND_PRIMARY = "#D6E4FF" as const;
/** Dark mode primary hover. */
export const COLOR_DARK_BRAND_PRIMARY_HOVER = "#E8F0FF" as const;
/** Dark mode accent — lighter blue for links. */
export const COLOR_DARK_BRAND_ACCENT = "#60A5FA" as const;
/** Dark mode accent hover. */
export const COLOR_DARK_BRAND_ACCENT_HOVER = "#93C5FD" as const;
/** Dark mode subtle primary — dark navy tint for branded backgrounds. */
export const COLOR_DARK_BRAND_PRIMARY_SUBTLE = "#1E2A45" as const;
/** Dark mode subtle accent — dark blue tint for highlighted backgrounds. */
export const COLOR_DARK_BRAND_ACCENT_SUBTLE = "#172554" as const;
/** Dark mode muted — subtle brand tint on dark. */
export const COLOR_DARK_BRAND_MUTED = "#1E2A3A" as const;
/** Dark mode page background. */
export const COLOR_DARK_SURFACE_BASE = "#0F1117" as const;
/** Dark mode secondary surface. */
export const COLOR_DARK_SURFACE_SUBTLE = "#161822" as const;
/** Dark mode tertiary surface. */
export const COLOR_DARK_SURFACE_MUTED = "#1E2030" as const;
/** Dark mode high-emphasis text (WCAG AA on #0F1117). */
export const COLOR_DARK_FOREGROUND_PRIMARY = "#F1F5F9" as const;
/** Dark mode supporting text (WCAG AA on #0F1117). */
export const COLOR_DARK_FOREGROUND_SECONDARY = "#94A3B8" as const;
/** Dark mode low-emphasis text. */
export const COLOR_DARK_FOREGROUND_TERTIARY = "#64748B" as const;
/** Dark mode text on light surfaces. */
export const COLOR_DARK_FOREGROUND_INVERSE = "#0F1117" as const;
/** Dark mode success — lighter green. */
export const COLOR_DARK_FEEDBACK_SUCCESS = "#4ADE80" as const;
/** Dark mode error — lighter red. */
export const COLOR_DARK_FEEDBACK_ERROR = "#F87171" as const;
/** Dark mode warning — lighter amber. */
export const COLOR_DARK_FEEDBACK_WARNING = "#FBBF24" as const;
/** Dark mode info — lighter sky. */
export const COLOR_DARK_FEEDBACK_INFO = "#38BDF8" as const;
/** Primary sans-serif typeface for UI and headings. */
export const FONTFAMILY_SANS: string[] = ["DM Sans","-apple-system","BlinkMacSystemFont","Segoe UI","Roboto","Helvetica Neue","Arial","sans-serif"];
/** Monospace typeface for code and technical content. */
export const FONTFAMILY_MONO: string[] = ["JetBrains Mono","SF Mono","Fira Code","Cascadia Code","monospace"];
/** Serif typeface for editorial and long-form content. Includes CJK (Japanese & Chinese) system font fallbacks. */
export const FONTFAMILY_SERIF: string[] = ["Noto Serif","Yu Mincho","YuMincho","MS PMincho","SimSun","Songti SC","serif"];
/** Largest heading size for hero and splash text. */
export const FONTSIZE_DISPLAY = "36px" as const;
/** Primary section heading. */
export const FONTSIZE_H1 = "24px" as const;
/** Secondary section heading. */
export const FONTSIZE_H2 = "18px" as const;
/** Tertiary heading / card title. */
export const FONTSIZE_H3 = "15px" as const;
/** Default body text. */
export const FONTSIZE_BODY = "15px" as const;
/** Figure notes and annotation text. */
export const FONTSIZE_CAPTION = "13px" as const;
/** Small labels and metadata. */
export const FONTSIZE_LABEL = "11px" as const;
/** Default body weight. */
export const FONTWEIGHT_REGULAR = 400 as const;
/** Medium emphasis. */
export const FONTWEIGHT_MEDIUM = 500 as const;
/** Subheading weight. */
export const FONTWEIGHT_SEMIBOLD = 600 as const;
/** Heading weight. */
export const FONTWEIGHT_BOLD = 700 as const;
/** Hero / display weight. */
export const FONTWEIGHT_EXTRABOLD = 800 as const;
/** Extra tight for display text. */
export const LINEHEIGHT_DISPLAY = 1.1 as const;
/** lineHeight/h1 */
export const LINEHEIGHT_H1 = 1.2 as const;
/** lineHeight/h2 */
export const LINEHEIGHT_H2 = 1.25 as const;
/** lineHeight/h3 */
export const LINEHEIGHT_H3 = 1.3 as const;
/** Extended reading body. */
export const LINEHEIGHT_BODY = 1.6 as const;
/** lineHeight/caption */
export const LINEHEIGHT_CAPTION = 1.45 as const;
/** lineHeight/label */
export const LINEHEIGHT_LABEL = 1.35 as const;
/** Tight leading for headings. */
export const LINEHEIGHT_TIGHT = 1.15 as const;
/** Comfortable reading. */
export const LINEHEIGHT_COMFORTABLE = 1.4 as const;
/** Extended reading body. */
export const LINEHEIGHT_READING = 1.6 as const;
/** Tight tracking for display. */
export const LETTERSPACING_TIGHT = "-0.03em" as const;
/** Snug tracking for headings. */
export const LETTERSPACING_SNUG = "-0.02em" as const;
/** Wide tracking for uppercase labels. */
export const LETTERSPACING_WIDE = "0.05em" as const;
/** Extra wide for all-caps metadata. */
export const LETTERSPACING_WIDER = "0.06em" as const;
/** Inline elements, tight icons. */
export const SPACING_XS = "4px" as const;
/** Tag padding, dense layout. */
export const SPACING_SM = "6px" as const;
/** Component internals, button padding. */
export const SPACING_MD = "12px" as const;
/** Between components, card padding. */
export const SPACING_LG = "24px" as const;
/** Section title margins, page gutters. */
export const SPACING_XL = "48px" as const;
/** Between major sections. */
export const SPACING_XXL = "80px" as const;
/** Default section vertical padding. */
export const SPACING_SECTION_Y = "80px" as const;
/** Max content width. */
export const SPACING_CONTAINER = "1040px" as const;
/** Navigation bar height. */
export const SPACING_NAV_H = "56px" as const;
/** Code inline, tight corners. */
export const BORDERRADIUS_TIGHT = "4px" as const;
/** Default button, input. */
export const BORDERRADIUS_DEFAULT = "8px" as const;
/** Card, container. */
export const BORDERRADIUS_CARD = "12px" as const;
/** Feature card, hero. */
export const BORDERRADIUS_FEATURE = "16px" as const;
/** Large container. */
export const BORDERRADIUS_LARGE = "24px" as const;
/** Pill / fully rounded. */
export const BORDERRADIUS_FULL = "9999px" as const;
/** Border ring for buttons and card hover states. */
export const SHADOW_RING = "0 0 0 1px #F3F4F6" as const;
/** Subtle elevation for cards and menus. */
export const SHADOW_WHISPER = "0 2px 16px rgba(0,0,0,0.04)" as const;
/** Color swatch preview height. */
export const SIZING_COLOR_SWATCH_H = "80px" as const;
/** Card visual block dimension. */
export const SIZING_CARD_VISUAL = "120px" as const;
/** Inline icon / swatch size. */
export const SIZING_ICON_INLINE = "20px" as const;
/** Hero decorative gradient dimension. */
export const SIZING_HERO_GRADIENT = "600px" as const;
/** Navigation bar stack order. */
export const ZINDEX_NAV = 100 as const;
/** Hover and micro-interactions. */
export const DURATION_FAST = "200ms" as const;
/** Accordion and panel transitions. */
export const DURATION_NORMAL = "300ms" as const;
/** Small / tablet portrait. */
export const BREAKPOINT_SM = "640px" as const;
/** Medium / tablet landscape. */
export const BREAKPOINT_MD = "768px" as const;
/** Large / desktop. */
export const BREAKPOINT_LG = "1024px" as const;
/** Extra large / wide desktop. */
export const BREAKPOINT_XL = "1280px" as const;

/** Flat map of all tokens keyed by slash-separated path */
export const tokens: Record<string, Token> = {
  "color/brand/primary": { value: COLOR_BRAND_PRIMARY, type: "color" },
  "color/brand/primary-hover": { value: COLOR_BRAND_PRIMARY_HOVER, type: "color" },
  "color/brand/primary-focus": { value: COLOR_BRAND_PRIMARY_FOCUS, type: "color" },
  "color/brand/primary-subtle": { value: COLOR_BRAND_PRIMARY_SUBTLE, type: "color" },
  "color/brand/secondary": { value: COLOR_BRAND_SECONDARY, type: "color" },
  "color/brand/secondary-hover": { value: COLOR_BRAND_SECONDARY_HOVER, type: "color" },
  "color/brand/secondary-focus": { value: COLOR_BRAND_SECONDARY_FOCUS, type: "color" },
  "color/brand/secondary-subtle": { value: COLOR_BRAND_SECONDARY_SUBTLE, type: "color" },
  "color/brand/accent": { value: COLOR_BRAND_ACCENT, type: "color" },
  "color/brand/accent-hover": { value: COLOR_BRAND_ACCENT_HOVER, type: "color" },
  "color/brand/accent-focus": { value: COLOR_BRAND_ACCENT_FOCUS, type: "color" },
  "color/brand/accent-subtle": { value: COLOR_BRAND_ACCENT_SUBTLE, type: "color" },
  "color/brand/muted": { value: COLOR_BRAND_MUTED, type: "color" },
  "color/brand/neutral": { value: COLOR_BRAND_NEUTRAL, type: "color" },
  "color/surface/base": { value: COLOR_SURFACE_BASE, type: "color" },
  "color/surface/subtle": { value: COLOR_SURFACE_SUBTLE, type: "color" },
  "color/surface/muted": { value: COLOR_SURFACE_MUTED, type: "color" },
  "color/foreground/primary": { value: COLOR_FOREGROUND_PRIMARY, type: "color" },
  "color/foreground/secondary": { value: COLOR_FOREGROUND_SECONDARY, type: "color" },
  "color/foreground/tertiary": { value: COLOR_FOREGROUND_TERTIARY, type: "color" },
  "color/foreground/inverse": { value: COLOR_FOREGROUND_INVERSE, type: "color" },
  "color/feedback/success/base": { value: COLOR_FEEDBACK_SUCCESS_BASE, type: "color" },
  "color/feedback/success/hover": { value: COLOR_FEEDBACK_SUCCESS_HOVER, type: "color" },
  "color/feedback/success/focus": { value: COLOR_FEEDBACK_SUCCESS_FOCUS, type: "color" },
  "color/feedback/success/subtle": { value: COLOR_FEEDBACK_SUCCESS_SUBTLE, type: "color" },
  "color/feedback/error/base": { value: COLOR_FEEDBACK_ERROR_BASE, type: "color" },
  "color/feedback/error/hover": { value: COLOR_FEEDBACK_ERROR_HOVER, type: "color" },
  "color/feedback/error/focus": { value: COLOR_FEEDBACK_ERROR_FOCUS, type: "color" },
  "color/feedback/error/subtle": { value: COLOR_FEEDBACK_ERROR_SUBTLE, type: "color" },
  "color/feedback/warning/base": { value: COLOR_FEEDBACK_WARNING_BASE, type: "color" },
  "color/feedback/warning/hover": { value: COLOR_FEEDBACK_WARNING_HOVER, type: "color" },
  "color/feedback/warning/focus": { value: COLOR_FEEDBACK_WARNING_FOCUS, type: "color" },
  "color/feedback/warning/subtle": { value: COLOR_FEEDBACK_WARNING_SUBTLE, type: "color" },
  "color/feedback/info/base": { value: COLOR_FEEDBACK_INFO_BASE, type: "color" },
  "color/feedback/info/hover": { value: COLOR_FEEDBACK_INFO_HOVER, type: "color" },
  "color/feedback/info/focus": { value: COLOR_FEEDBACK_INFO_FOCUS, type: "color" },
  "color/feedback/info/subtle": { value: COLOR_FEEDBACK_INFO_SUBTLE, type: "color" },
  "color/dark/brand/primary": { value: COLOR_DARK_BRAND_PRIMARY, type: "color" },
  "color/dark/brand/primary-hover": { value: COLOR_DARK_BRAND_PRIMARY_HOVER, type: "color" },
  "color/dark/brand/accent": { value: COLOR_DARK_BRAND_ACCENT, type: "color" },
  "color/dark/brand/accent-hover": { value: COLOR_DARK_BRAND_ACCENT_HOVER, type: "color" },
  "color/dark/brand/primary-subtle": { value: COLOR_DARK_BRAND_PRIMARY_SUBTLE, type: "color" },
  "color/dark/brand/accent-subtle": { value: COLOR_DARK_BRAND_ACCENT_SUBTLE, type: "color" },
  "color/dark/brand/muted": { value: COLOR_DARK_BRAND_MUTED, type: "color" },
  "color/dark/surface/base": { value: COLOR_DARK_SURFACE_BASE, type: "color" },
  "color/dark/surface/subtle": { value: COLOR_DARK_SURFACE_SUBTLE, type: "color" },
  "color/dark/surface/muted": { value: COLOR_DARK_SURFACE_MUTED, type: "color" },
  "color/dark/foreground/primary": { value: COLOR_DARK_FOREGROUND_PRIMARY, type: "color" },
  "color/dark/foreground/secondary": { value: COLOR_DARK_FOREGROUND_SECONDARY, type: "color" },
  "color/dark/foreground/tertiary": { value: COLOR_DARK_FOREGROUND_TERTIARY, type: "color" },
  "color/dark/foreground/inverse": { value: COLOR_DARK_FOREGROUND_INVERSE, type: "color" },
  "color/dark/feedback/success": { value: COLOR_DARK_FEEDBACK_SUCCESS, type: "color" },
  "color/dark/feedback/error": { value: COLOR_DARK_FEEDBACK_ERROR, type: "color" },
  "color/dark/feedback/warning": { value: COLOR_DARK_FEEDBACK_WARNING, type: "color" },
  "color/dark/feedback/info": { value: COLOR_DARK_FEEDBACK_INFO, type: "color" },
  "fontFamily/sans": { value: FONTFAMILY_SANS, type: "fontFamily" },
  "fontFamily/mono": { value: FONTFAMILY_MONO, type: "fontFamily" },
  "fontFamily/serif": { value: FONTFAMILY_SERIF, type: "fontFamily" },
  "fontSize/display": { value: FONTSIZE_DISPLAY, type: "dimension" },
  "fontSize/h1": { value: FONTSIZE_H1, type: "dimension" },
  "fontSize/h2": { value: FONTSIZE_H2, type: "dimension" },
  "fontSize/h3": { value: FONTSIZE_H3, type: "dimension" },
  "fontSize/body": { value: FONTSIZE_BODY, type: "dimension" },
  "fontSize/caption": { value: FONTSIZE_CAPTION, type: "dimension" },
  "fontSize/label": { value: FONTSIZE_LABEL, type: "dimension" },
  "fontWeight/regular": { value: FONTWEIGHT_REGULAR, type: "number" },
  "fontWeight/medium": { value: FONTWEIGHT_MEDIUM, type: "number" },
  "fontWeight/semibold": { value: FONTWEIGHT_SEMIBOLD, type: "number" },
  "fontWeight/bold": { value: FONTWEIGHT_BOLD, type: "number" },
  "fontWeight/extrabold": { value: FONTWEIGHT_EXTRABOLD, type: "number" },
  "lineHeight/display": { value: LINEHEIGHT_DISPLAY, type: "number" },
  "lineHeight/h1": { value: LINEHEIGHT_H1, type: "number" },
  "lineHeight/h2": { value: LINEHEIGHT_H2, type: "number" },
  "lineHeight/h3": { value: LINEHEIGHT_H3, type: "number" },
  "lineHeight/body": { value: LINEHEIGHT_BODY, type: "number" },
  "lineHeight/caption": { value: LINEHEIGHT_CAPTION, type: "number" },
  "lineHeight/label": { value: LINEHEIGHT_LABEL, type: "number" },
  "lineHeight/tight": { value: LINEHEIGHT_TIGHT, type: "number" },
  "lineHeight/comfortable": { value: LINEHEIGHT_COMFORTABLE, type: "number" },
  "lineHeight/reading": { value: LINEHEIGHT_READING, type: "number" },
  "letterSpacing/tight": { value: LETTERSPACING_TIGHT, type: "dimension" },
  "letterSpacing/snug": { value: LETTERSPACING_SNUG, type: "dimension" },
  "letterSpacing/wide": { value: LETTERSPACING_WIDE, type: "dimension" },
  "letterSpacing/wider": { value: LETTERSPACING_WIDER, type: "dimension" },
  "spacing/xs": { value: SPACING_XS, type: "dimension" },
  "spacing/sm": { value: SPACING_SM, type: "dimension" },
  "spacing/md": { value: SPACING_MD, type: "dimension" },
  "spacing/lg": { value: SPACING_LG, type: "dimension" },
  "spacing/xl": { value: SPACING_XL, type: "dimension" },
  "spacing/xxl": { value: SPACING_XXL, type: "dimension" },
  "spacing/section-y": { value: SPACING_SECTION_Y, type: "dimension" },
  "spacing/container": { value: SPACING_CONTAINER, type: "dimension" },
  "spacing/nav-h": { value: SPACING_NAV_H, type: "dimension" },
  "borderRadius/tight": { value: BORDERRADIUS_TIGHT, type: "dimension" },
  "borderRadius/default": { value: BORDERRADIUS_DEFAULT, type: "dimension" },
  "borderRadius/card": { value: BORDERRADIUS_CARD, type: "dimension" },
  "borderRadius/feature": { value: BORDERRADIUS_FEATURE, type: "dimension" },
  "borderRadius/large": { value: BORDERRADIUS_LARGE, type: "dimension" },
  "borderRadius/full": { value: BORDERRADIUS_FULL, type: "dimension" },
  "shadow/ring": { value: SHADOW_RING, type: "shadow" },
  "shadow/whisper": { value: SHADOW_WHISPER, type: "shadow" },
  "sizing/color-swatch-h": { value: SIZING_COLOR_SWATCH_H, type: "dimension" },
  "sizing/card-visual": { value: SIZING_CARD_VISUAL, type: "dimension" },
  "sizing/icon-inline": { value: SIZING_ICON_INLINE, type: "dimension" },
  "sizing/hero-gradient": { value: SIZING_HERO_GRADIENT, type: "dimension" },
  "zIndex/nav": { value: ZINDEX_NAV, type: "number" },
  "duration/fast": { value: DURATION_FAST, type: "duration" },
  "duration/normal": { value: DURATION_NORMAL, type: "duration" },
  "breakpoint/sm": { value: BREAKPOINT_SM, type: "dimension" },
  "breakpoint/md": { value: BREAKPOINT_MD, type: "dimension" },
  "breakpoint/lg": { value: BREAKPOINT_LG, type: "dimension" },
  "breakpoint/xl": { value: BREAKPOINT_XL, type: "dimension" },
};

/** Token values mapped to CSS custom property names */
export const cssVariables: Record<string, string | number | readonly string[]> = {
  "--color-brand-primary": COLOR_BRAND_PRIMARY,
  "--color-brand-primary-hover": COLOR_BRAND_PRIMARY_HOVER,
  "--color-brand-primary-focus": COLOR_BRAND_PRIMARY_FOCUS,
  "--color-brand-primary-subtle": COLOR_BRAND_PRIMARY_SUBTLE,
  "--color-brand-secondary": COLOR_BRAND_SECONDARY,
  "--color-brand-secondary-hover": COLOR_BRAND_SECONDARY_HOVER,
  "--color-brand-secondary-focus": COLOR_BRAND_SECONDARY_FOCUS,
  "--color-brand-secondary-subtle": COLOR_BRAND_SECONDARY_SUBTLE,
  "--color-brand-accent": COLOR_BRAND_ACCENT,
  "--color-brand-accent-hover": COLOR_BRAND_ACCENT_HOVER,
  "--color-brand-accent-focus": COLOR_BRAND_ACCENT_FOCUS,
  "--color-brand-accent-subtle": COLOR_BRAND_ACCENT_SUBTLE,
  "--color-brand-muted": COLOR_BRAND_MUTED,
  "--color-brand-neutral": COLOR_BRAND_NEUTRAL,
  "--color-surface-base": COLOR_SURFACE_BASE,
  "--color-surface-subtle": COLOR_SURFACE_SUBTLE,
  "--color-surface-muted": COLOR_SURFACE_MUTED,
  "--color-foreground-primary": COLOR_FOREGROUND_PRIMARY,
  "--color-foreground-secondary": COLOR_FOREGROUND_SECONDARY,
  "--color-foreground-tertiary": COLOR_FOREGROUND_TERTIARY,
  "--color-foreground-inverse": COLOR_FOREGROUND_INVERSE,
  "--color-feedback-success-base": COLOR_FEEDBACK_SUCCESS_BASE,
  "--color-feedback-success-hover": COLOR_FEEDBACK_SUCCESS_HOVER,
  "--color-feedback-success-focus": COLOR_FEEDBACK_SUCCESS_FOCUS,
  "--color-feedback-success-subtle": COLOR_FEEDBACK_SUCCESS_SUBTLE,
  "--color-feedback-error-base": COLOR_FEEDBACK_ERROR_BASE,
  "--color-feedback-error-hover": COLOR_FEEDBACK_ERROR_HOVER,
  "--color-feedback-error-focus": COLOR_FEEDBACK_ERROR_FOCUS,
  "--color-feedback-error-subtle": COLOR_FEEDBACK_ERROR_SUBTLE,
  "--color-feedback-warning-base": COLOR_FEEDBACK_WARNING_BASE,
  "--color-feedback-warning-hover": COLOR_FEEDBACK_WARNING_HOVER,
  "--color-feedback-warning-focus": COLOR_FEEDBACK_WARNING_FOCUS,
  "--color-feedback-warning-subtle": COLOR_FEEDBACK_WARNING_SUBTLE,
  "--color-feedback-info-base": COLOR_FEEDBACK_INFO_BASE,
  "--color-feedback-info-hover": COLOR_FEEDBACK_INFO_HOVER,
  "--color-feedback-info-focus": COLOR_FEEDBACK_INFO_FOCUS,
  "--color-feedback-info-subtle": COLOR_FEEDBACK_INFO_SUBTLE,
  "--color-dark-brand-primary": COLOR_DARK_BRAND_PRIMARY,
  "--color-dark-brand-primary-hover": COLOR_DARK_BRAND_PRIMARY_HOVER,
  "--color-dark-brand-accent": COLOR_DARK_BRAND_ACCENT,
  "--color-dark-brand-accent-hover": COLOR_DARK_BRAND_ACCENT_HOVER,
  "--color-dark-brand-primary-subtle": COLOR_DARK_BRAND_PRIMARY_SUBTLE,
  "--color-dark-brand-accent-subtle": COLOR_DARK_BRAND_ACCENT_SUBTLE,
  "--color-dark-brand-muted": COLOR_DARK_BRAND_MUTED,
  "--color-dark-surface-base": COLOR_DARK_SURFACE_BASE,
  "--color-dark-surface-subtle": COLOR_DARK_SURFACE_SUBTLE,
  "--color-dark-surface-muted": COLOR_DARK_SURFACE_MUTED,
  "--color-dark-foreground-primary": COLOR_DARK_FOREGROUND_PRIMARY,
  "--color-dark-foreground-secondary": COLOR_DARK_FOREGROUND_SECONDARY,
  "--color-dark-foreground-tertiary": COLOR_DARK_FOREGROUND_TERTIARY,
  "--color-dark-foreground-inverse": COLOR_DARK_FOREGROUND_INVERSE,
  "--color-dark-feedback-success": COLOR_DARK_FEEDBACK_SUCCESS,
  "--color-dark-feedback-error": COLOR_DARK_FEEDBACK_ERROR,
  "--color-dark-feedback-warning": COLOR_DARK_FEEDBACK_WARNING,
  "--color-dark-feedback-info": COLOR_DARK_FEEDBACK_INFO,
  "--fontFamily-sans": FONTFAMILY_SANS,
  "--fontFamily-mono": FONTFAMILY_MONO,
  "--fontFamily-serif": FONTFAMILY_SERIF,
  "--fontSize-display": FONTSIZE_DISPLAY,
  "--fontSize-h1": FONTSIZE_H1,
  "--fontSize-h2": FONTSIZE_H2,
  "--fontSize-h3": FONTSIZE_H3,
  "--fontSize-body": FONTSIZE_BODY,
  "--fontSize-caption": FONTSIZE_CAPTION,
  "--fontSize-label": FONTSIZE_LABEL,
  "--fontWeight-regular": FONTWEIGHT_REGULAR,
  "--fontWeight-medium": FONTWEIGHT_MEDIUM,
  "--fontWeight-semibold": FONTWEIGHT_SEMIBOLD,
  "--fontWeight-bold": FONTWEIGHT_BOLD,
  "--fontWeight-extrabold": FONTWEIGHT_EXTRABOLD,
  "--lineHeight-display": LINEHEIGHT_DISPLAY,
  "--lineHeight-h1": LINEHEIGHT_H1,
  "--lineHeight-h2": LINEHEIGHT_H2,
  "--lineHeight-h3": LINEHEIGHT_H3,
  "--lineHeight-body": LINEHEIGHT_BODY,
  "--lineHeight-caption": LINEHEIGHT_CAPTION,
  "--lineHeight-label": LINEHEIGHT_LABEL,
  "--lineHeight-tight": LINEHEIGHT_TIGHT,
  "--lineHeight-comfortable": LINEHEIGHT_COMFORTABLE,
  "--lineHeight-reading": LINEHEIGHT_READING,
  "--letterSpacing-tight": LETTERSPACING_TIGHT,
  "--letterSpacing-snug": LETTERSPACING_SNUG,
  "--letterSpacing-wide": LETTERSPACING_WIDE,
  "--letterSpacing-wider": LETTERSPACING_WIDER,
  "--spacing-xs": SPACING_XS,
  "--spacing-sm": SPACING_SM,
  "--spacing-md": SPACING_MD,
  "--spacing-lg": SPACING_LG,
  "--spacing-xl": SPACING_XL,
  "--spacing-xxl": SPACING_XXL,
  "--spacing-section-y": SPACING_SECTION_Y,
  "--spacing-container": SPACING_CONTAINER,
  "--spacing-nav-h": SPACING_NAV_H,
  "--borderRadius-tight": BORDERRADIUS_TIGHT,
  "--borderRadius-default": BORDERRADIUS_DEFAULT,
  "--borderRadius-card": BORDERRADIUS_CARD,
  "--borderRadius-feature": BORDERRADIUS_FEATURE,
  "--borderRadius-large": BORDERRADIUS_LARGE,
  "--borderRadius-full": BORDERRADIUS_FULL,
  "--shadow-ring": SHADOW_RING,
  "--shadow-whisper": SHADOW_WHISPER,
  "--sizing-color-swatch-h": SIZING_COLOR_SWATCH_H,
  "--sizing-card-visual": SIZING_CARD_VISUAL,
  "--sizing-icon-inline": SIZING_ICON_INLINE,
  "--sizing-hero-gradient": SIZING_HERO_GRADIENT,
  "--zIndex-nav": ZINDEX_NAV,
  "--duration-fast": DURATION_FAST,
  "--duration-normal": DURATION_NORMAL,
  "--breakpoint-sm": BREAKPOINT_SM,
  "--breakpoint-md": BREAKPOINT_MD,
  "--breakpoint-lg": BREAKPOINT_LG,
  "--breakpoint-xl": BREAKPOINT_XL,
};
