import { readdirSync, readFileSync, writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const componentsDir = join(__dirname, "../src/components");
const indexFile = join(__dirname, "../src/index.ts");

const files = readdirSync(componentsDir)
  .filter((f) => f.endsWith(".vue"))
  .sort();

const lines = [];
lines.push('import "./index.css";');
lines.push("// Auto-generated by build — do not edit manually");

for (const file of files) {
  const filePath = join(componentsDir, file);
  const content = readFileSync(filePath, "utf-8");
  const componentName = file.replace(".vue", "");

  // Component export
  lines.push(`export { default as ${componentName} } from "./components/${file}";`);

  // Extract all exported interfaces for type re-exports
  const interfaceRegex = /export interface (\w+)/g;
  const typeNames = [];
  let match;
  while ((match = interfaceRegex.exec(content)) !== null) {
    typeNames.push(match[1]);
  }

  if (typeNames.length > 0) {
    lines.push(`export type { ${typeNames.join(", ")} } from "./components/${file}";`);
  }
}

// Type exports from .ts type-definition files
const tsFiles = readdirSync(componentsDir)
  .filter((f) => f.endsWith(".ts"))
  .sort();

for (const file of tsFiles) {
  const filePath = join(componentsDir, file);
  const content = readFileSync(filePath, "utf-8");
  const tsInterfaceRegex = /export interface (\w+)/g;
  const tsTypeNames = [];
  let tsMatch;
  while ((tsMatch = tsInterfaceRegex.exec(content)) !== null) {
    tsTypeNames.push(tsMatch[1]);
  }
  if (tsTypeNames.length > 0) {
    lines.push(`export type { ${tsTypeNames.join(", ")} } from "./components/${file}";`);
  }
}

// Non-component exports (composables) — appended at the end
lines.push('export { useToast } from "./composables/useToast"');
lines.push('export type { ToastItem, ToastContext } from "./composables/useToast";');
lines.push('export { useForm } from "./composables/useMizuField";');
lines.push('export type { FieldState, MizuFormResult } from "./composables/useMizuField";');
lines.push("");

writeFileSync(indexFile, lines.join("\n"));
console.log(`Generated ${indexFile} — ${files.length} components`);
