import "./index.css";
// Auto-generated by build — do not edit manually
export { default as MizuButton } from "./components/MizuButton.vue";
export type { ButtonProps } from "./components/MizuButton.vue";
