import "./index.css";
// Auto-generated by build — do not edit manually
export { default as MizunagiButton } from "./components/MizunagiButton.vue";
export type { ButtonProps } from "./components/MizunagiButton.vue";
